###
GET http://localhost:3000/organization/5e970a8cc6f4ed280c6defe8/project
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJzdWIiOiI1ZTkwYmI4OGVmNWE4MTU2ZWVjMDZmM2QiLCJpYXQiOjE1ODY5NjAzOTcsImV4cCI6MTU4Njk2Mzk5N30.IO9pwyX5r1M5Of8UkF3HALkluXHx7VBwihdTaifqy_4

###
POST http://localhost:3000/organization/5e970a8cc6f4ed280c6defe8/project
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJzdWIiOiI1ZTkwYmI4OGVmNWE4MTU2ZWVjMDZmM2QiLCJpYXQiOjE1ODY5NjAzOTcsImV4cCI6MTU4Njk2Mzk5N30.IO9pwyX5r1M5Of8UkF3HALkluXHx7VBwihdTaifqy_4

{
  "name": "new Project"
}
