###
GET http://localhost:3000/organization/5e8a580ff0b9edc691ef1c2e/project
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJzdWIiOiI1ZThhNTdmM2YwYjllZGM2OTFlZjFjMmMiLCJpYXQiOjE1ODYzNTY2ODQsImV4cCI6MTU4NjM2MDI4NH0.BXbxsOBNAjIOEQiqOGqfdGp_ZADc-2vTn2amJHAMw3c

###
POST http://localhost:3000/organization/5e8a580ff0b9edc691ef1c2e/project
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJzdWIiOiI1ZTkwYmI4OGVmNWE4MTU2ZWVjMDZmM2QiLCJpYXQiOjE1ODY1NDYzOTcsImV4cCI6MTU4NjU0OTk5N30.86anDSmpKMMTbAU0OM2mVAbejRzgHpo3HviEF5M7rjE

{
  "_id": "5e90bb88ef5a8156eec06f3d",
    "email": "test@test.com",
    "firstName": "John",
    "lastName": "Wick",
    "lastLoginDttm": "2020-04-10T18:32:11.831Z",
    "organizations": {},
    "groups": {},
    "createdDttm": "2020-04-10T18:31:36.440Z",
    "updatedDttm": "2020-04-10T18:32:11.832Z",
    "__v": 0
}
