###
GET http://localhost:3000/users

###
GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJzdWIiOiI1ZThhNTdmM2YwYjllZGM2OTFlZjFjMmMiLCJpYXQiOjE1ODYzNTY2ODQsImV4cCI6MTU4NjM2MDI4NH0.BXbxsOBNAjIOEQiqOGqfdGp_ZADc-2vTn2amJHAMw3c

###
GET http://localhost:3000/users/5e80b4d0650f406b469fbb41
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJzdWIiOiI1ZTgwYjRkMDY1MGY0MDZiNDY5ZmJiNDEiLCJpYXQiOjE1ODU3NDYwNjAsImV4cCI6MTU4NTc0OTY2MH0.OGNp9zS3bL9EXbSE0NFRepbQXz1Qfc1NAbTInUp2CoM

###

PATCH http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJzdWIiOiI1ZTgwYjRkMDY1MGY0MDZiNDY5ZmJiNDEiLCJpYXQiOjE1ODU3NDYwNjAsImV4cCI6MTU4NTc0OTY2MH0.OGNp9zS3bL9EXbSE0NFRepbQXz1Qfc1NAbTInUp2CoM

{
  "_id": "5e80b4d0650f406b469fbb41",
  "email": "test@test.com",
  "firstName": "Johnathan"
}